### PR TITLE
Create Meeting 72

### PR DESCRIPTION
**Pull request by KenMan79**
Create Meeting #72

### CODE REVIEW

**Comment by poojaranjan** [comment]
@KenMan79 please make the following changes

image

**To do**: Rename these as agenda items, they aren't decisions.

image

**To do**: Format it into different paragraphs based on the agenda items for clear understanding. Same for ECH updates. It has multiple sub section in the agenda. Please format it accordingly.

**To do**: Replace "Superette Gupta" with "Supreet Gupta"

Thanks!

**Comment by KenMan79** [comment]
Will do so @poojaranjan 👍

**Comment by mryalamanchi** [comment]
Hello @KenMan79. Are the suggested changes made?

**Comment by KenMan79** [comment]
Yes let me recheck once more @mryalamanchi

**Comment by poojaranjan** [comment]
Merging this for record because it has been sitting for a while. 
We welcome any pull request to update this notes.

**Pull request merged**
