### PR TITLE
Create AllCoreDevs Notes & Summaries.md

### PR DESCRIPTION
**Pull request by timbeiko**
For us to track who is responsible for producing the summaries for which CoreDev call

### CODE REVIEW

**Comment by poojaranjan** [comment]
I am not sure if we necessarily need a [summary tracker]( https://github.com/ethereum-cat-herders/PM/blob/4c8e6799dbe20a764dd280f32c46d21facbf3b1a/AllCoreDevs%20Notes%20%26%20Summaries.md) for AllCoreDevs Notes.

Note taking task is already taken care at [ECH PM repo]( https://github.com/ethereum-cat-herders/PM/issues) as issue #. 

[Guideline]( https://github.com/ethereum/pm/issues/69) says that summary should be posted within 24 hrs and transcript within a week and in my experience, it is being taken care.  

If someone is interested in sharing immediately after the meeting; are welcome to share. This decision  can be managed through internal communication. The need of calendar or tracker for that, I am not so sure.

**Comment by mariapaulafn** [comment]
@poojaranjan @timbeiko just dropping a line for you to ping me when you approved, so I can publish on Magi and other fora :)

**Comment by mariapaulafn** [comment]
@timbeiko I believe this is very helpful - if Brett or others continue to do the summary, great, but we need a backup plan and imo this works

**Comment by timbeiko** [comment]
@mariapaulafn so you think having this on the repo vs. coordinating on Gitter is beneficial? What do you think @DBrettRobertson?

**Comment by mariapaulafn** [comment]
I think both are needed - some of us have a lot on our plates :)

**Comment by CPSTL** [comment]
IMHO it would be easiest for the Note Taker of the AllCoreDevs call to do the summary as well. If we really want to do track who is doing it, why don't we just track the Note Taker?

**For two reasons:** 
1. Paying the Note Taker is already managed through Gitcoin bounties and we can simply add the summary writing task to that bounty.  
2. The Note Taker has everything fresh in their mind which makes it easier for them to do it right away.

Please note that the Note Taking bounty for AllCoreDevs calls is public and people simply apply to do it and get accepted based on their application. We can always share the bounty across all channels as a backup. WDYT?

**Comment by timbeiko** [comment]
I agree it is probably easier for the notetaker to do a summary and submit it for review as a PR, as Brett did for the last call. I don't want to create yet-another channel of comms if it isn't useful. @mariapaulafn you were most in favor of this. WDYT of @CPSTL's comment above? If you agree, I would just close and delete this PR.

**Comment by mariapaulafn** [comment]
Sure, i agree - ill do my part and post on social media and magicians

**Pull request closed without merging**
